name: CLI container-less on Windows

inputs:
  tier:
    description: |
      Test TIER name
    required: false
    type: string
    default: TIER0
  maven_token:
    description: |
      Token for public github maven repo access
    required: false
    type: string
    default: ""

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-java@v4
    with:
      distribution: 'microsoft'
      java-version: '21'
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.12'

  - name: Get kantra bundle
    uses: actions/download-artifact@v4
    with:
      name: kantra-bundle
      path: C:\Users\runneradmin\.kantra

  - name: Install test dependencies
    shell: cmd
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      mkdir ${{ github.workspace }}\report

  - name: Run TIER0 analysis test
    shell: pwsh
    run: |
      set KANTRA_CLI_PATH=C:\Users\runneradmin\.kantra\windows-kantra.exe
      set REPORT_OUTPUT_PATH=${{ github.workspace }}\report
      set PROJECT_PATH=${{ github.workspace }}
      set GIT_PASSWORD=${{ inputs.maven_token }}

      pytest -s tests/analysis/java/test_tier0.py

      cd D:\a\kantra-cli-tests\kantra-cli-tests\report\tackle-testap-public-cloud-readiness
      mvn -s D:\a\kantra-cli-tests\kantra-cli-tests\data\tmp\tackle-testap-public-cloud-readiness_settings.xml clean package

  - name: Save analysis output
    uses: actions/upload-artifact@v4
    if: always()
    with:
      name: kantra-outputs-windows-containerless
      path: ${{ github.workspace }}\report
