name: CLI container-less on Linux

inputs:
  tier:
    description: |
      Test TIER name
    required: false
    type: string
    default: TIER0
  maven_token:
    description: |
      Token for public github maven repo access
    required: false
    type: string
    default: ""

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-java@v4
    with:
      distribution: 'microsoft'
      java-version: '21'

  - name: Get kantra bundle
    uses: actions/download-artifact@v4
    with:
      name: kantra-bundle
      path: /home/runner/.kantra

  - name: Configure Test Environment
    shell: bash
    run: |
      chmod +x /home/runner/.kantra/kantra
      ln -s /home/runner/.kantra /home/runner/.config/.kantra
      mkdir ${{ github.workspace }}/report
    working-directory: ${{ github.workspace }}
  - name: Install test dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Run TIER0 analysis test
    shell: bash
    run: |
      export KANTRA_CLI_PATH=/home/runner/.kantra/kantra
      export REPORT_OUTPUT_PATH=${{ github.workspace }}/report
      export PROJECT_PATH=${{ github.workspace }}
      export GIT_PASSWORD=${{ inputs.maven_token }}

      pytest -s tests/analysis/java/test_tier0.py

      cd D:\a\kantra-cli-tests\kantra-cli-tests\report\tackle-testap-public-cloud-readiness
      mvn -s D:\a\kantra-cli-tests\kantra-cli-tests\data\tmp\tackle-testap-public-cloud-readiness_settings.xml clean package

  - name: Save analysis output
    uses: actions/upload-artifact@v4
    if: always()
    with:
      name: kantra-outputs-linux-containerless
      path: ${{ github.workspace }}/report
